# Generated by Django 4.1 on 2022-09-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_product_alert_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_discount_allow',
            field=models.FloatField(default=0),
        ),
    ]
